name = "raven-worker"
main = "src/index.ts"
compatibility_date = "2023-01-25"
logpush = true
routes = [
	{ pattern = "raven.bcharity.net", custom_domain = true }
]
keep_vars = true

[env.production.vars]
DATADOG_TOKEN = ""
